import { createRoot } from 'react-dom/client';
import '../../src/app/globals.css';
import '../../src/app/family-theme.css';
import AppShell from '../../src/components/AppShell';
import { ViewportObserver } from '../../src/components/ViewportObserver';
import { Toaster } from '../../src/components/ui/toaster';
import Home from '../../src/app/page';
import Ledger from '../../src/app/ledger/page';
import Dashboard from '../../src/app/ledger/dashboard/page';
import Bills from '../../src/app/bills/page';
import Settlement from '../../src/app/settlement/page';
import History from '../../src/app/settlement/history/page';
import Calendar from '../../src/app/calendar/page';
import Stickies from '../../src/app/stickies/page';
import Sticky from '../../src/app/stickies/[id]/page';
import Categories from '../../src/app/settings/categories/page';
import Methods from '../../src/app/settings/payment-methods/page';
import Merchants from '../../src/app/settings/merchants/page';
import Payers from '../../src/app/settings/payers/page';
import Backup from '../../src/app/settings/backup/page';
import Login from '../../src/app/login/page';
import { installFixtures } from './fixtures';
installFixtures();
const routes = { '/': Home, '/ledger': Ledger, '/ledger/dashboard': Dashboard, '/bills': Bills, '/settlement': Settlement, '/settlement/history': History, '/calendar': Calendar, '/stickies': Stickies, '/stickies/sticky-1': Sticky, '/settings/categories': Categories, '/settings/payment-methods': Methods, '/settings/merchants': Merchants, '/settings/payers': Payers, '/settings/backup': Backup, '/login': Login };
const Page = routes[location.pathname] ?? Home;
createRoot(document.getElementById('root')).render(<><ViewportObserver /><AppShell><Page /></AppShell><Toaster /></>);
